### ISSUE TITLE
No se debería usar Floats para lidiar con precios

### ISSUE THREAD

**Issue by maxcodes** [compropago/compropago-ruby#6]
Hola! He notado que en su código ejemplo están usando Floats para pedir el precio:

https://github.com/compropago/compropago-ruby/blob/master/example/example.rb#L5

```
Compropago::Charge.create({ order_price: 10000.0, # <---
                             order_name: "SAMSUNG GOLD CURL",
                             customer_name: "Roberto Miranda",
                             customer_email: "noreply@compropago.com",
                             payment_type: "OXXO"})
```

Esto no se debe hacer porque los Floats no son suficientemente precisos y pueden llevar a errores de redondeo. Ver https://spin.atomicobject.com/2014/08/14/currency-rounding-errors/ y https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency/3730040#3730040 para una explicación más profunda.

**Comment by danteay** [comment]
Gracias por las observaciones esas cuestiones ya se tienen contempladas, por el momento se esta generando una nueva version de la gema.

**Comment by maxcodes** [comment]
Excelente, gracias!
